feature: add new bool property withClasses that add classes to rows
jorrit/react-hyper-responsive-table pull request #6
Opened 2018-07-11 09:04 UTC by MariannaMilovanova

2018-07-24 15:40 UTC, jorrit requested changes
Thanks for your PR, Marianna. Could you take a look at these review comments and address them? Thanks!

2018-07-24 15:40 UTC, jorrit commented on tests/index-test.js
> +const withClasses = true;
Please move this line into the test function.

2018-07-24 15:40 UTC, jorrit commented on src/index.js
> +  return withClasses ? { className: `th-${key}` } : {};
I think `header-${key}` is more descriptive than `th-${key}`.

2018-07-24 15:40 UTC, jorrit commented on src/index.js
> +
I think `row-${key}` is more descriptive than `row-${key}`.

2018-07-24 15:40 UTC, jorrit commented on README.md
> +| `withClasses` | `bool` | Add classNames to each rows and headers cells by using keyGetter function. |
Please change to 'Add unique class names to each row and header cell, respectively `row-KEY` and `header-KEY`.'.

2018-09-05 10:55 UTC, MariannaMilovanova commented
@jorrit please see may changes

2018-09-17 08:03 UTC, jorrit approved these changes

2018-09-17 08:04 UTC, merged

2018-09-17 09:07 UTC, jorrit commented
My apologies for the delay. 0.6.0 has been released with this feature. Thanks for your contribution!

2018-09-19 13:15 UTC, MariannaMilovanova commented
Thank you!